### ISSUE TITLE
Plugin crashes on start of PhpStorm 2019.2.3

### ISSUE THREAD

**Issue by axelitus** [kevinlinxp/intellij-sublime-snippets-support#5]
PhpStorm crashes when loading and throws the following error:

```
Plugin 'com.kevinlinxp.sublimeSnippetsSupport' failed to initialize and will be disabled.  Please restart PhpStorm.

java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/axel/ExpanDrive/Box/Courses & Certifications/2016 - Diplomado Consultoría Aplicada en Administración de TI/Módulo 09/Material/Alineación.pdf
    at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87)
    at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)
    at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
    at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    at com.kevinlinxp.sublimeSnippetsSupport.SublimeSnippetsSupportSettings.reloadSublimeSnippetsAsLiveTemplates(SublimeSnippetsSupportSettings.kt:69)
    at com.kevinlinxp.sublimeSnippetsSupport.PluginRegistration.initComponent(PluginRegistration.kt:14)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414)
    at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.nio.file.NoSuchFileException: /home/axel/ExpanDrive/Box/Courses & Certifications/2016 - Diplomado Consultoría Aplicada en Administración de TI/Módulo 09/Material/Alineación.pdf
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
    at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
    at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:145)
    at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
    at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
    at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
    at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
    at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
    at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83)
    ... 34 more
```

The problem may be related to issue #3 

I'm using Ubuntu 19.04 with the latest updates. My Sublime Text Packages folder is `~/.config/sublime-text-3/Packages`

I tried to set the directory manually, but when the plugin is disabled there's no option to do so.

**Comment by axelitus** [comment]
I have looked around but I cannot seem to find any place where a settings file is stored (trying on a Windows machine that can load the plugin). I did find a place where my folder is found in the config folder: `.PhpStorm2019.2\system\LocalHistory\changes.storageData`, this is a binary file and from the name of it I don't think the config is stored here. If you could tell me where the setting is store maybe I could set it manually to have it loaded.

**Comment by axelitus** [comment]
Alright! Found it: `.PhpStorm2019.2\config\options\sublimeSnippetsSupport.xml`

I have created the file with the following content:

```xml
<application>
  <component name="SublimeSnippetsSupportSettings">
    <option name="sublimeSnippetsRoot" value="/home/axel/.config/sublime-text-3/Packages" />
  </component>
</application>
```

But it seems that the plugin is trying to read my whole user folder still.

**Comment by axelitus** [comment]
False alarm! I got the filename wrong (missed the s from Snippets). It is working now!

I think that this should be documented somewhere to help other users that are having the same issue.

**Comment by kevinlinxp** [comment]
Hi @axelitus,

Thank you very much for reporting the issue and finding the workaround.

And I realised scanning from the user home is not a good idea.

Just upload a new version 1.2.7 for fixing the issue and be more defensive to IOExceptions. It would take 2-3 days for JetBrains to approve it.

Thanks again :)

Regards,
Kevin

**Comment by axelitus** [comment]
Great to hear!

Indeed looking for the files in all the user home directory is not the best option (out of performance alone).

With the configuration file, it is working fine though. I still think it would be good to have this documented somewhere because if no config change is made, the file is never created and is hard to figure out what to do when the plugin crashes the whole app.

**Comment by axelitus** [comment]
Maybe the best way to tackle this would be to create the file on the first run regardless and set the root folder to the calculated value depending on OS. Subsequent calls will take the configuration file value and if the path is incorrect it can be easily fixed with a text editor.

I'm not sure (not tried yet) if with the new guarded code the IDE is able to start and the plugin is not disabled, therefore the option to change the path is available. That would solve it as well.
